### ISSUE TITLE
Options documentation and how-to

### ISSUE THREAD

**Issue by Jackbennett** [NHellFire/dban#21]
Just looking for what all the options are and what they do. I found the isolinux.cfg file with options to APPEND.

Just wondering what others there are, what exactly `silent` does and how do you pass those if I'm PXE booting like so:

```
LABEL wipe
    MENU LABEL Wipe Drive
    #MENU PASSWD $nicetry/$
    KERNEL /memdisk
    APPEND iso initrd=/dban-3.0.1_i586.iso
```

**Comment by NHellFire** [comment]
`silent` stops it from showing kernel messages on the console, so that they don't overwrite the wipe display. As it looks like you're using PXELINUX, you can extract the ISO and copy/paste from isolinux.cfg to pxelinux.cfg, changing paths as required.
The `nuke` argument sets the command it runs at startup, allowing you to specify your own defaults (more examples in isolinux.cfg and when booted, the config menu will tell you the arguments for that setting).

**Comment by Jackbennett** [comment]
Fantastic. ok I had to extract the BZI and boot that, not mount the ISO though in a memdisk.

For reference I changed to;
```
# test-new Wipe a HDD
LABEL wipe
    MENU LABEL Test Wipe Drive
    KERNEL ../../images/DBAN.BZI
    APPEND nuke="dwipe --autonuke --method dod522022m" silent vga=785
```
That path is weird because this is booting from MDT.

Is there a switch to disable networking or configure the reporting services? I'd love a list of progress status by MAC address. But at least turning it off I could start faster.

**Comment by NHellFire** [comment]
You can disable networking with `ip=none`
Newer builds configure network in background, so it won't slow down boot.
Currently there isn't any network logging, other than untested TFTP after completion. Need to do some work on that but not sure what's best for it.
